fix: Prevent Nuke from opening multiple submitter dialogs
aws-deadline/deadline-cloud-for-nuke pull request #17
Opened 2023-09-11 20:49 UTC by jlangmann-aws

### What was the problem/requirement? (What/Why)
Issue: Bea-15149
Previously, a user could open multiple submitter dialogs. The user should not be able to open more than 1 submitter dialog.

### What was the solution? (How)
If the submitter dialog is already open, refresh the dialog properties (including job attachments). 

### What is the impact of this change?
Better user experience

### How was this change tested?
Job Bundle Output tests were successful

### Did you run the "Job Bundle Output Tests"? If not, why not? If so, paste the test results here.
Yes, ran tests. Also tested adding/removing read node dependencies and re-opening the Submitter dialog. 

```
Required: paste the contents of job_bundle_output_tests/test-job-bundle-results.txt here
```
only diff was my Nuke version (I'm using 14v5)

### Was this change documented?

### Is this a breaking change?
This change is dependent on - https://github.com/casillas2/deadline-cloud/pull/35

2023-09-11 22:54 UTC, mwiebe requested changes

2023-09-11 22:54 UTC, mwiebe commented on src/deadline/nuke_submitter/deadline_submitter_for_nuke.py
> +        g_submitter_dialog.refresh(auto_detected_attachments, attachments)
I think we'll want render_settings to be part of this refresh as well. If we're refreshing an existing dialog, it may be necessary to move the job_bundle_callback out of this function to no longer be a closure. This is because after updating this, the callback is still a closure to the first call that created the dialog, not any of the later updates.

2023-09-11 23:36 UTC, jlangmann-aws commented on src/deadline/nuke_submitter/deadline_submitter_for_nuke.py
> +        g_submitter_dialog.refresh(auto_detected_attachments, attachments)
Makes sense, happy to do this while I'm at it. It will also be a slightly larger change in `deadline-cloud` since we'll need to add refresh functions for the Shared Job Settings and the Job Specific Settings UIs.

2023-09-12 16:57 UTC, jlangmann-aws commented on src/deadline/nuke_submitter/deadline_submitter_for_nuke.py
> +        g_submitter_dialog.refresh(auto_detected_attachments, attachments)
Updated this and the deadline-cloud PR so we're now passing in the render settings. It looks like the `job_bundle_callback` is valid as is since we're passing in the settings (which are reset if necessary) when submitting a job or saving a bundle. 

Also I see that the test coverage went slightly low with python 3.10. I can merge in this PR after Ting's review https://github.com/casillas2/deadline-cloud-for-nuke/pull/18 is complete!

2023-09-15 01:27 UTC, amznestebanpapp approved these changes

2023-09-15 16:25 UTC, tincheng approved these changes

2023-09-18 20:04 UTC, agerveshi approved these changes

2023-09-21 18:17 UTC, mwiebe approved these changes

2023-09-21 18:17 UTC, merged