fix: adaptor wheel error dialog and unit test coverage
aws-deadline/deadline-cloud-for-nuke pull request #18
Opened 2023-09-11 22:56 UTC by tincheng

### What was the problem/requirement? (What/Why)
- Unit test coverage needed improvement
- There was a small bug where if we tried to submit without setting up wheel directory but had "developer options: include adaptor wheels" selected, then it gave a generic `FileNotFoundError` instead of the intended `The Developer Option 'Include Adaptor Wheels' is enabled, but the wheels directory does not exist` message

### What was the solution? (How)
- increased unit test coverage to ~77%
- changed the check for directory to rely on just `is_dir()` instead of `exists()`

### What is the impact of this change?
Better test coverage and small fix for user experience

### How was this change tested?
- coverage updated from `hatch run test`
- locally verified that intended Deadline error message was shown in UI instead of FileNotFound error

### Did you run the "Job Bundle Output Tests"? If not, why not? If so, paste the test results here.
No - I was not able to run the Job Bundle Output Tests on Mac. Got ```Failed 2 tests, succeeded 0.
See the file /Users/tincheng/workplace/deadline-cloud-for-nuke/job_bundle_output_tests/test-job-bundle-results.txt for a full report.``` and the output file was blank. Probably need more time to get the bundle tests working on Mac, but I think this PR should have low impact without this as changes are either just unit tests or had been verified within DCC. 

```
Required: paste the contents of job_bundle_output_tests/test-job-bundle-results.txt here
```

### Was this change documented?
No

### Is this a breaking change?
No

2023-09-13 23:33 UTC, rmv commented on test/deadline_adaptor_for_nuke/unit/NukeAdaptor/test_adaptor.py
> +    @pytest.mark.parametrize("regex_index, stdout, expected_progress", handle_progess_params)
typo -> should be handle_progress_params, maybe fix in rest of instances?

2023-09-14 19:35 UTC, agerveshi approved these changes

2023-09-14 19:35 UTC, agerveshi commented on test/deadline_adaptor_for_nuke/unit/NukeAdaptor/test_adaptor.py
> +class TestNukeAdaptor_get_major_minor_version:
Do we know what actually calls `_get_major_minor_version`? I see that all of the adapters implement it, but what is it used for?

2023-09-14 19:35 UTC, agerveshi commented on test/deadline_submitter_for_nuke/unit/test_deadline_submitter_for_nuke.py
> +        return_value=Path("/some/path.deadline_settings.json"),
This path is hard-coded a few times, is there a way to get the return value from the fixture in the other locations rather than duplicating it?

2023-09-14 19:35 UTC, agerveshi commented on test/deadline_submitter_for_nuke/unit/test_template_output/expected_job_template_output.py
> +EXPECTED_NUKE_JOB_TEMPLATE = {
Maybe add a comment on how you generated this template to make it easier for others to update it in the future?

2023-09-15 22:36 UTC, tincheng commented on test/deadline_adaptor_for_nuke/unit/NukeAdaptor/test_adaptor.py
> +    @pytest.mark.parametrize("regex_index, stdout, expected_progress", handle_progess_params)
fixed!

2023-09-15 22:38 UTC, tincheng commented on test/deadline_adaptor_for_nuke/unit/NukeAdaptor/test_adaptor.py
> +class TestNukeAdaptor_get_major_minor_version:
it is not currently used! I saw an internal ticket in the backlog on using this function instead of a hard-coded DCC version, so this function was likely added in preparation for that task.

2023-09-15 22:39 UTC, tincheng commented on test/deadline_submitter_for_nuke/unit/test_deadline_submitter_for_nuke.py
> +        return_value=Path("/some/path.deadline_settings.json"),
Sure, I will make it into a constant

2023-09-15 22:48 UTC, tincheng commented on test/deadline_submitter_for_nuke/unit/test_template_output/expected_job_template_output.py
> +EXPECTED_NUKE_JOB_TEMPLATE = {
That's a good question. I generated this template under the assumption that the current implementation was correct. So the templates here used for comparison were simply generated by calls to `_get_job_template()`, then pasting the results. Ideally if people make only small changes in the future, they will not need to update the whole template, and can just fix the small parts that become different. If there are large changes to the whole template, it may be easier to re-generate the template and overriding the existing one and just check diff to make sure the changes look reasonable.

2023-09-18 20:46 UTC, amznestebanpapp commented on test/deadline_submitter_for_nuke/unit/test_template_output/expected_job_template_output.py
> +EXPECTED_NUKE_JOB_TEMPLATE = {
instead of putting the whole output in a str, I would suggest to have it as a file and make the test load the file and extract the contents. There is a vscode plugin to help write these templates, so it is easier to have it as a file directly

2023-09-18 20:46 UTC, amznestebanpapp approved these changes

2023-09-18 21:38 UTC, rmv approved these changes
LGTM (though I'm new to this testing setup)

2023-09-18 21:38 UTC, rmv commented on test/deadline_adaptor_for_nuke/unit/NukeAdaptor/test_adaptor.py
> +class TestNukeAdaptor_get_major_minor_version:
Missing type hints in these methods

2023-09-18 21:39 UTC, tincheng commented on test/deadline_submitter_for_nuke/unit/test_template_output/expected_job_template_output.py
> +EXPECTED_NUKE_JOB_TEMPLATE = {
Changed the files to json in latest commit

2023-09-18 21:39 UTC, tincheng commented on test/deadline_submitter_for_nuke/unit/test_template_output/expected_job_template_output.py
> +EXPECTED_NUKE_JOB_TEMPLATE = {
Changed the files to json in latest commit

2023-09-18 21:57 UTC, jlangmann-aws approved these changes

2023-09-18 22:30 UTC, mwiebe requested changes

2023-09-18 22:30 UTC, mwiebe commented on test/deadline_submitter_for_nuke/unit/test_deadline_submitter_for_nuke.py
> +    _get_sticky_settings_file,
We're going to have conflicts to resolve on these ones with https://github.com/casillas2/deadline-cloud-for-nuke/pull/24, as I simplified the sticky setting logic.

2023-09-18 22:30 UTC, mwiebe commented on test/deadline_submitter_for_nuke/unit/test_deadline_submitter_for_nuke.py
> +    RenderSubmitterSettings,
Same here, I removed this dataclass.

2023-09-18 22:30 UTC, mwiebe commented on test/deadline_submitter_for_nuke/unit/test_deadline_submitter_for_nuke.py
> +            os.path.dirname(__file__), "test_expected_output_json/expected_job_template_output.json"
Hmm, I'd prefer we don't do anything like this in our unit tests. The job bundle output tests serve this purpose, and we should rely exclusively on them instead. In particular, we should add those tests to our CI/CD pipeline.

Why is adding tests like this bad? The testing coverage gains are not flexible for the purpose of the code - they instead lock down the implementation details. So when we do a refactor that keeps the same functionality but dramatically changes the shape of the job templates, these need to be re-generated. The job bundle output tests have a built-in mechanism for that: You delete the folder and re-run the test, it generates the output again, and you validate it by hand. These json files don't work the same way.

Could you remove these tests for now? Maybe we can re-evaluate them, but first I want the job bundle outputs in our CI/CD pipeline. A useful change would be to add coverage analysis to those job bundle output tests. Then we could combine the coverage data from them with the coverage data from the unit tests to evaluate our overall coverage metric.

2023-09-18 22:48 UTC, tincheng commented on test/deadline_submitter_for_nuke/unit/test_deadline_submitter_for_nuke.py
> +            os.path.dirname(__file__), "test_expected_output_json/expected_job_template_output.json"
I have removed these tests for now, and will take a look into job bundle test coverage analysis.

2023-09-18 22:50 UTC, tincheng commented on test/deadline_submitter_for_nuke/unit/test_deadline_submitter_for_nuke.py
> +    _get_sticky_settings_file,
Ah! will rebase again

2023-09-19 00:14 UTC, tincheng commented on test/deadline_submitter_for_nuke/unit/test_deadline_submitter_for_nuke.py
> +    RenderSubmitterSettings,
I saw that load_sticky and save_sticky were moved there, but I won't add new tests for them this time

2023-09-19 01:03 UTC, mwiebe approved these changes

2023-09-19 01:04 UTC, merged