feat: [Nuke] Added MOV support
aws-deadline/deadline-cloud-for-nuke pull request #46
Opened 2023-10-24 21:32 UTC by jlangmann-aws

### What was the problem/requirement? (What/Why)
Previously the nuke submitter was not able to handle rendering "MOV" renders. The submitter could only support single frame renders rather than handle rendering out a frame range in a single task.

### What was the solution? (How)
The solution adds basic "MOV" render functionality to the submitter. If a "MOV" render is detected via the write node, a single task is generated for the job. 

If MOV is detected:
1. Remove the parameter definition "Frame" from the step
2. Update the script data with the "frameRange" as specified by the frame range.

These template changes result in a single task being created

### What is the impact of this change?

Add support for MOV rendering!

### How was this change tested?

Yes.
1. Tested rendering out a file sequence (exr) to verify existing functionality
2. Tested rendering out a mov file to verify that a single task was created

From both of the tests above I also verified the generated output in Nuke

### Did you run the "Job Bundle Output Tests"? If not, why not? If so, paste the test results here.

```

Timestamp: 2023-10-24T21:31:25.428295+00:00
Running job bundle output test: /home/rocky/git/deadline-cloud-for-nuke/job_bundle_output_tests/multi-load-save

multi-load-save
Test succeeded

Timestamp: 2023-10-24T21:31:25.682390+00:00
Running job bundle output test: /home/rocky/git/deadline-cloud-for-nuke/job_bundle_output_tests/noise-saver

noise-saver
Test succeeded

Timestamp: 2023-10-24T21:31:25.857324+00:00
Running job bundle output test: /home/rocky/git/deadline-cloud-for-nuke/job_bundle_output_tests/cwd-path

cwd-path
Test succeeded

Timestamp: 2023-10-24T21:31:26.048854+00:00
Running job bundle output test: /home/rocky/git/deadline-cloud-for-nuke/job_bundle_output_tests/ocio

ocio
Test succeeded

Timestamp: 2023-10-24T21:31:26.255416+00:00
Running job bundle output test: /home/rocky/git/deadline-cloud-for-nuke/job_bundle_output_tests/group-read

group-read
Test succeeded

All tests passed, ran 5 total.
Timestamp: 2023-10-24T21:31:28.318128+00:00

```

### Was this change documented?
No

### Is this a breaking change?
No

2023-10-24 22:19 UTC, amznestebanpapp approved these changes

2023-10-24 22:19 UTC, amznestebanpapp commented on src/deadline/nuke_submitter/deadline_submitter_for_nuke.py
> +                        frame_list
you can use f-string formatting here

2023-10-24 22:19 UTC, amznestebanpapp commented on src/deadline/nuke_submitter/deadline_submitter_for_nuke.py
> +                )
same here

2023-10-24 22:54 UTC, mwiebe requested changes

2023-10-24 22:54 UTC, mwiebe commented on src/deadline/nuke_adaptor/NukeClient/nuke_handler.py
> +        end_frame = data["endframe"] if data.get("endframe") is not None else start_frame
nit: Could simplify to:

```python
end_frame = data.get("endframe", start_frame)
```

2023-10-24 22:54 UTC, mwiebe commented on src/deadline/nuke_adaptor/NukeAdaptor/schemas/run_data.schema.json
> +        "endframe": {"type": "number"}
Daniel and I have discussed how to generalize OpenJD with chunking, and one conclusion we reached is for the chunked version of `onRun` to accept a range expression in a string instead of an integer. We could plan ahead for that development by replacing "frame" with "frameRange", and having it be a range expression conforming to the OpenJD spec. To simplify things, we can require that initially it either is an integer `"<frame>"` or an interval `"<startframe>-<endframe>"`.

If you want to proceed with this, in this PR you would start a two-phase change by making both "frame" and "frameRange" work, while marking "frame" as deprecated. Once that change is rolled out, you would make another PR to remove "frame".

2023-10-24 22:54 UTC, mwiebe commented on src/deadline/nuke_submitter/deadline_submitter_for_nuke.py
> +        mov_render = "file_type" in write_node.knobs() and write_node["file_type"].value() == "mov"
Does "mov" fully characterize movie rendering, or is it only for the Quicktime "mov" extension? Are there "mpeg" and other formats too?

2023-10-25 15:28 UTC, jlangmann-aws commented on src/deadline/nuke_adaptor/NukeAdaptor/schemas/run_data.schema.json
> +        "endframe": {"type": "number"}
FrameRange likely won't work right now though with parameterization, right, until OpenJD supports chunking?

I could simply replace "endframe" with "frameRange" if it makes the upcoming transition easier. We would only use "frameRange" for "MOV" related renders, and single frame renders would still use "frame". Does that align with what you're thinking?

2023-10-25 15:32 UTC, jlangmann-aws commented on src/deadline/nuke_submitter/deadline_submitter_for_nuke.py
> +        mov_render = "file_type" in write_node.knobs() and write_node["file_type"].value() == "mov"
Yes, "mov" characterizes rendering out a file with a "mov" extension. The other available options in Nuke are for rendering single frame images, I don't see any other "movie" related formats (there is no "mpeg" option).

2023-10-26 17:07 UTC, mwiebe commented on src/deadline/nuke_adaptor/NukeAdaptor/schemas/run_data.schema.json
> +        "endframe": {"type": "number"}
FrameRange will work fine before OpenJD supports chunking. Replacing both "frame" and "endframe" with "frameRange" will make the upcoming transition smoother. Better to make the one simpler interface instead of bifurcating it.

2023-10-30 23:42 UTC, jlangmann-aws commented on src/deadline/nuke_adaptor/NukeAdaptor/schemas/run_data.schema.json
> +        "endframe": {"type": "number"}
If we're going to use FrameRange for both mov and single frame workflows, how do we support having this value be two different types? ex: an integer "<frame>" or range string "<startframe-endframe>"? I don't see how we could set a key to have optional types in the run_data.schema.json.

EDIT: ignore the above, looks like multiple types can be defined via `"type": ["number", "string"] ` in the schema.

2023-11-01 22:24 UTC, mwiebe requested changes

2023-11-01 22:24 UTC, mwiebe commented on src/deadline/nuke_adaptor/NukeAdaptor/schemas/run_data.schema.json
> +        "frameRange": { "type": ["number", "string"] }
I think at this point we need to start doing two-phase deployments for changes like this. What that means is the change to do right now is to:

1. Keep "frame", but instead of making it required, make it optional.
2. Add "frameRange", but keep it optional.

This way, the adaptor can accept submissions from the old submitter using "frame" and the new submitter using "frameRange." The change represents the start of phase 1.

Once all the submitters are updated to submit "frameRange" instead of "frame", we will do another PR that removes "frame" from the schema and changes "frameRange" from optional to required.

2023-11-01 22:24 UTC, mwiebe commented on src/deadline/nuke_adaptor/NukeAdaptor/adaptor.py
> +            Action("start_render", {"frameRange": run_data["frameRange"]})
In the first step of the two-phase deployment, I think something like this would accept both "frameRange" and "frame":

```python
# Before the enqueue_action
if "frameRange" not in run_data and "frame" not in run_data:
    raise ... # exception that one of the two is required.
...
 Action("start_render", {"frameRange": run_data.get("frameRange", str(run_data.get("frame", ""))})
```

2023-11-01 22:24 UTC, mwiebe commented on src/deadline/nuke_adaptor/NukeClient/nuke_handler.py
> +        if isinstance(frame_range, int):
Due to the schema enforcement, this will always be a string. Maybe use `if "-" not in frame_range` and then validate that the string can be converted to an integer.

2023-11-01 22:24 UTC, mwiebe commented on src/deadline/nuke_submitter/deadline_submitter_for_nuke.py
> +        mov_render = "file_type" in write_node.knobs() and write_node["file_type"].value() == "mov"
I decided to take a peek at that list, and only by going through them one by one discovered that "mxf" is also a movie format. It gives options for Avid codecs.

2023-11-01 22:24 UTC, mwiebe commented on src/deadline/nuke_submitter/default_nuke_job_template.yaml
> +      data: 'frameRange: {{Task.Param.Frame}}'
The value here should be a string instead of a number due to the schema. Putting the value in double quotes can do that:

```yaml
 data: 'frameRange: "{{Task.Param.Frame}}"'
```

2023-11-01 22:24 UTC, mwiebe commented on test/unit/deadline_adaptor_for_nuke/NukeAdaptor/test_adaptor.py
> +    return {"frameRange": 42}
I think this should be `return {"frameRange": "42"}`

2023-11-01 22:27 UTC, mwiebe commented on src/deadline/nuke_adaptor/NukeAdaptor/schemas/run_data.schema.json
> +        "frameRange": { "type": ["number", "string"] }
Here's a link to reading material about two-phase deployments if you want to go deeper on the topic: https://aws.amazon.com/builders-library/ensuring-rollback-safety-during-deployments/

2023-11-01 23:02 UTC, jlangmann-aws commented on src/deadline/nuke_adaptor/NukeClient/nuke_handler.py
> +        if isinstance(frame_range, int):
I tested this out and the schema enforcement does allow for both int or string. I will go ahead and test to see if the parameterization works with string as well, then we can remove the integer option.

2023-11-01 23:44 UTC, mwiebe approved these changes

2023-11-02 16:56 UTC, mwiebe approved these changes

2023-11-02 20:56 UTC, amznestebanpapp approved these changes

2023-11-02 22:33 UTC, merged